# -*- coding: utf-8 -*-
"""Atividade01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgpTNkMAmGlQo6GA80K_BfvodTlEgQ32
"""

# ==================================================
# Atividade 01 - Inteligência Artificial
# ==================================================

# 1. IMPORTAÇÕES
import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings('ignore')

print("Bibliotecas importadas com sucesso!")

# 2. CONFIGURAÇÕES INICIAIS

TICKERS = ["TSLA", "AAPL", "PETR4.SA", "WEGE3.SA", "ITUB4.SA"]
START_DATE = "2015-01-01"
WINDOW_SIZE = 30 # OS DIAS DE LOOKBACK
TRAIN_SPLIT = 0.8 # 80% TREINO E 20% TESTE

print(f"Ações selecionadas: {TICKERS}")
print(f"Período: {START_DATE} até hoje")
print(f"Janela temporal: {WINDOW_SIZE} dias")

# 3. FUNÇÕES AUXILIARES

def ciar_janelas(data, window_size):
  #Cria sequências de janelas temporais
  X, y = [], []
  for i in range(len(data) - window_size):
    X.append(data[i:i + window_size])
    y.append(data[i + window_size])
  return np.array(X), np.array(y)

def criar_modelo_lstm(window_size):
  # Constói modelo LSTM
  model = Sequential([
      LSTM(50, activation='tanh', input_shape=(window_size, 1))
  ])
  model.compile(otimizer='adam', loss='mse')
  return model

print('Funções criadas!')